### ISSUE TITLE
Nimbly Lite checklist

### ISSUE THREAD

**Issue by dmh** [Resultify/nimbly-lite#42]
6 Page Templates

- [x] Home
- [x] About
- [x] Contact
- [x] Blog list
- [x] Blog post

7 System Templates

- [x] 404
- [x] 500
- [x] Password prompt template
- [x] Subscription template
- [x] Subscriptions update template
- [x] Backup unsubscribe template
- [x] Search results template

24 Modules

- [x] Audio
- [x] Blog list
- [x] Blog pagination
- [x] Blog recent
- [x] Blog related
- [x] Button
- [x] Card
- [x] F.A.Q.
- [x] Heading
- [x] Hero Image
- [x] Icon
- [x] Image | Card
- [x] Image
- [x] Link
- [x] RichText
- [x] Site header
- [x] Social links
- [x] SVG divider
- [x] Divider
- [x] Text
- [x] Form

Sections
depend on design
