### ISSUE TITLE
Nimbly Pro checklist

### ISSUE THREAD

**Issue by dmh** [Resultify/nimbly-lite#43]
?? Page Templates

- [ ] Home
- [ ] About
- [ ] Contact
- [ ] Blog list
- [ ] + Blog list Pro
- [ ] Blog post
- [ ] + Blog post Pro
- [ ] + Event list
- [ ] + Event details
- [ ] Landing page
- [ ] + Landing page 2
- [ ] + Product
- [ ] + Pricing
- [ ] + Documentation
- [ ] + Filter content ????
- [ ] + Downloads

10 System Templates

- [ ] 404
- [ ] 500
- [ ] Password prompt template
- [ ] Subscription template
- [ ] Subscriptions update template
- [ ] Backup unsubscribe template
- [ ] Search results template
- [ ] + Search results template Pro
- [ ] + Membership login
- [ ] + Membership registration

?? Modules

- [x] Audio
- [ ] + Video
- [x] Blog list
- [x] Blog pagination
- [x] Blog recent
- [x] Blog related
- [ ] + Blog Comments
- [ ] + Blog Email Subscription
- [ ] + Post Filter
- [ ] Button
- [x] Card
- [ ] F.A.Q.
- [x] Heading
- [ ] Hero Image
- [x] Icon
- [ ] Image | Card
- [x] Image
- [ ] Link
- [x] RichText
- [ ] Site header
- [ ] Social links
- [ ] + Follow Me links vs Social links
- [ ] + Social Sharing vs Follow Me links vs Social links
- [ ] SVG divider
- [ ] Divider
- [x] Text
- [ ] Form
- [ ] Logo
- [ ] Site Search Input
- [ ] Site Search result
- [ ] + Image slider
- [ ] + Image Gallery
- [ ] + Pricing Cards
- [ ] + Tabs
- [ ] + Accordion
- [ ] + Meetings
- [ ] + Events
- [ ] + Menu
- [ ] + Simple menu
- [ ] + Breadcrumbs
- [ ] + HTML module
- [ ] + RSS List
- [ ] + ... depend on design

Sections
depend on design
